questions =  [
    {"id": 0, "question": "The world would be a better place if all humanity worked toward a single purpose.", "effects": {"right": 1}},
    {"id": 1, "question": "Assuming God exists, humans can be closer to God by working together.", "effects": {"right": 1}},
    {"id": 2, "question": "There is a higher order in the universe towards which all thought and evolution ultimately trends.", "effects": {"right": 1}},
    {"id": 3, "question": "It is \"human nature\" to need control over others.", "effects": {"right": 1}},
    {"id": 4, "question": "Diversity is only beneficial when everyone is working toward a shared goal.", "effects": {"right": 1}},
    {"id": 5, "question": "If everyone was a complete individualist, society would fall apart.", "effects": {"right": 1}},
    {"id": 6, "question": "The idea of humans working together like ants in a colony is comforting to me.", "effects": {"right": 1}},
    {"id": 7, "question": "If I was offered the chance rule the world with supreme authority, I would accept.", "effects": {"right": 1}},
    {"id": 8, "question": "Any attempt to subject another to one's will is an act against not just society but the universe as a whole.", "effects": {"right": -1}},
    {"id": 9, "question": "A society that maximizes freedom is one that works best for everyone.", "effects": {"right": -1}},
    {"id": 10, "question": "Trying to get human beings to work towards a common purpose is a waste of time.", "effects": {"right": -1}},
    {"id": 11, "question": "We should share things with others because we want to, not because we feel we have to.", "effects": {"right": -1}},
    {"id": 12, "question": "The idea of a collective consciousness or hive mind is really scary to me.", "effects": {"right": -1}},
    {"id": 13, "question": "The universe fundamentally favors the maximization of human potential.", "effects": {"right": -1}},
    {"id": 14, "question": "Spiritual fulfilment is ultimately personal, we each strive towards a higher power on our own.", "effects": {"right": -1}},
    {"id": 15, "question": "In the grand scheme of things, the way we implement our goals is more important than the goals themselves.", "effects": {"auth": 1}},
    {"id": 16, "question": "People independently striving toward efficiently reaching the same goal will often find that their methods converge.", "effects": {"auth": 1}},
    {"id": 17, "question": "When something has been shown to work better, everyone should adopt it.", "effects": {"auth": 1}},
    {"id": 18, "question": "It's wasteful and confounding that we all have different units and standards.", "effects": {"auth": 1}},
    {"id": 19, "question": "Having a universal language would greatly benefit all of humanity.", "effects": {"auth": 1}},
    {"id": 20, "question": "There is an optimal set of methods that are favored by the universe.", "effects": {"auth": 1}},
    {"id": 21, "question": "Society is about what we have in common rather than what we accomplish.", "effects": {"auth": 1}},
    {"id": 22, "question": "If everyone had total agency over their appearance and abilites, diversity would vanish completely.", "effects": {"auth": 1}},
    {"id": 23, "question": "A lot of inefficiency is prefereable to a lot of uniformity.", "effects": {"auth": -1}},
    {"id": 24, "question": "It is impossible for a human being to reach their potential following the methods used by another.", "effects": {"auth": -1}},
    {"id": 25, "question": "There is no way that diversity could ever possibly hurt any endeavor.", "effects": {"auth": -1}},
    {"id": 26, "question": "It is more rewarding to succeed despite differences are more rewarding than to compensate for differences.", "effects": {"auth": -1}},
    
    {"id": 27, "question": "The government should, at most, provide emergency services and law enforcement.", "effects": {"auth": -1}},
    {"id": 28, "question": "The police were not created to protect the people, but to uphold the status quo by force.", "effects": {"auth": -1}},
    {"id": 29, "question": "State schools are a bad idea because our state shouldn't be influencing our children.", "effects": {"auth": -1}},
    {"id": 30, "question": "Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.", "effects": {"prog": 1}},
    {"id": 31, "question": "An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"prog": 1}},
    {"id": 32, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"prog": 1}},
    {"id": 33, "question": "Nudism is perfectly natural.", "effects": {"prog": 1}},
    {"id": 34, "question": "Animals deserve certain universal rights.", "effects": {"prog": 1}},
    {"id": 35, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"prog": 1}},
    {"id": 36, "question": "Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"prog": 1}},
    {"id": 37, "question": "Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"prog": 1}},
    {"id": 38, "question": "Homosexuality is against my values.", "effects": {"prog": -1}},
    {"id": 39, "question": "Transgender individuals should not be able to adopt children.", "effects": {"prog": -1}},
    {"id": 40, "question": "Drugs are harmful and should be banned.", "effects": {"prog": -1}},
    {"id": 41, "question": "The death penalty should exist for certain crimes.", "effects": {"prog": -1}},
    {"id": 42, "question": "Victimless crimes should still be punished.", "effects": {"prog": -1}},
    {"id": 43, "question": "One cannot be moral without religion.", "effects": {"prog": -1}},
    {"id": 44, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"prog": -1}},
    {"id": 45, "question": "Multiculturalism is bad.", "effects": {"prog": -1}}
];
