questions =  [
    {"id": 0, "question": "The world would be a better place if all humanity worked toward a single purpose.", "effects": {"right": 1}},
    {"id": 1, "question": "Assuming God exists, humans can get closer to God by working together.", "effects": {"right": 1}},
    {"id": 2, "question": "There is a higher order in the universe towards which all thought and evolution ultimately trends.", "effects": {"right": 1}},
    {"id": 3, "question": "It is \"human nature\" to need control over others.", "effects": {"right": 1}},
    {"id": 4, "question": "Diversity is only beneficial when everyone is working toward a shared goal.", "effects": {"right": 1}},
    {"id": 5, "question": "If everyone was a complete individualist, society would fall apart.", "effects": {"right": 1}},
    {"id": 6, "question": "The idea of humans working together like ants in a colony is comforting to me.", "effects": {"right": 1}},
    {"id": 7, "question": "If I was offered the chance rule the world with supreme authority, I would accept.", "effects": {"right": 1}},
    {"id": 8, "question": "Any attempt to subject another to one's will is an act against not just society but the universe as a whole.", "effects": {"right": -1}},
    {"id": 9, "question": "A society that maximizes freedom is one that works best for everyone.", "effects": {"right": -1}},
    {"id": 10, "question": "Trying to get human beings to work towards a common purpose is a waste of time.", "effects": {"right": -1}},
    {"id": 11, "question": "We should share things with others because we want to, not because we feel we have to.", "effects": {"right": -1}},
    {"id": 12, "question": "The idea of a collective consciousness or hive mind is really scary to me.", "effects": {"right": -1}},
    {"id": 13, "question": "The universe fundamentally favors the maximization of human potential.", "effects": {"right": -1}},
    {"id": 14, "question": "Spiritual fulfilment is ultimately personal, we each strive towards a higher power on our own.", "effects": {"right": -1}},
    {"id": 15, "question": "We should adapt ourselves to new environments rather than trying to change them to suit our own needs.", "effects": {"auth": 1}},
    {"id": 16, "question": "People independently striving toward efficiently reaching the same goal will often find that their methods converge.", "effects": {"auth": 1}},
    {"id": 17, "question": "When something has been shown to work better, everyone should adopt it.", "effects": {"auth": 1}},
    {"id": 18, "question": "It's wasteful and confounding that we all have different units and standards.", "effects": {"auth": 1}},
    {"id": 19, "question": "Having a universal language would greatly benefit all of humanity.", "effects": {"auth": 1}},
    {"id": 20, "question": "There is an optimal set of methods that are favored by the universe.", "effects": {"auth": 1}},
    {"id": 21, "question": "Society is about what we have in common rather than what we accomplish.", "effects": {"auth": 1}},
    {"id": 22, "question": "If everyone had total agency over their appearance and abilites, diversity would vanish completely.", "effects": {"auth": 1}},
    {"id": 23, "question": "A lot of inefficiency is prefereable to a lot of uniformity.", "effects": {"auth": -1}},
    {"id": 24, "question": "It is impossible for a human being to reach their potential following the methods used by another.", "effects": {"auth": -1}},
    {"id": 25, "question": "There is no way that diversity could ever possibly hurt any endeavor.", "effects": {"auth": -1}},
    {"id": 26, "question": "Trying to adapt our society to new environment is a waste of time.", "effects": {"auth": -1}},
    {"id": 27, "question": "There is as much value in keeping the old ways of doing things as adopting new ones.", "effects": {"auth": -1}},
    {"id": 28, "question": "Working out issues of compatibility creates an overall more robust system.", "effects": {"auth": -1}},
    {"id": 29, "question": "The ability to integrate new people is more important than overall cohesiveness of society.", "effects": {"auth": -1}},
    {"id": 30, "question": "The machines we create are the best representation of human progress as a whole.", "effects": {"prog": 1}},
    {"id": 31, "question": "Progress is made by transcending the limits of our biological nature.", "effects": {"prog": 1}},
    {"id": 32, "question": "It would be disgusting if my house, car, phone, washing machine, and computer were living things.", "effects": {"prog": 1}},
    {"id": 33, "question": "Trying to adapt living things to roles that machines already perform better is a waste of time.", "effects": {"prog": 1}},
    {"id": 34, "question": "It will always be more efficient to assemble something than to wait for something to grow.", "effects": {"prog": 1}},
    {"id": 35, "question": "Biology is just a tiny subset of Chemistry, and Chemistry is just a tiny subset of Physics.", "effects": {"prog": 1}},
    {"id": 36, "question": "Trying to get our technology to mimic living things is a waste of time and makes them inefficient.", "effects": {"prog": 1}},
    {"id": 37, "question": "I would be excited to upgrade my own body with electronic parts.", "effects": {"prog": 1}},
    {"id": 38, "question": "There is no reason to invent a machine to do something that a living thing can do.", "effects": {"prog": -1}},
    {"id": 39, "question": "I would feel more empathy towards my computer or my phone if it was a living breathing thing.", "effects": {"prog": -1}},
    {"id": 40, "question": "We live more authentically when in touch with our nature as organic living things", "effects": {"prog": -1}},
    {"id": 41, "question": "The cycle of birth, consumption, exretion, reproduction, death, and decay is valuable or even desirable.", "effects": {"prog": -1}},
    {"id": 42, "question": "There is something really special about the carbon molecule, beyond its physical properties.", "effects": {"prog": -1}},
    {"id": 43, "question": "If machines could be better than living things, machines would have evolved instead of organic life.", "effects": {"prog": -1}},
    {"id": 44, "question": "If a limb or organ had to be removed from my body, I would prefer to have it grown back than mechanically replaced, even if the prosthesis somehow worked better.", "effects": {"prog": -1}},
    {"id": 45, "question": "Machines will never be more efficient than living things.", "effects": {"prog": -1}}
];
